### ISSUE TITLE
iniciarNido TVar type diff

### ISSUE THREAD

**Issue by FedeGB** [FedeGB/7559-TP2#2]
Al querer iniciar el nido en el menu, tira que la grilla que estoy pasando tiene como el tercer valor de tupla un valor distinto al que está esperando. (le paso un Integer y está esperando un a10).
El problema es probable que sea como se está inicializando ese valor en cada tupla de la grilla.

**Comment by mafvidal** [comment]
No vi bien el problema, pero ojo, que al crear con esto: "(x,y,Memoria.crear 0)" lo que se crea es:
(Int, Int, IO(Tvar)) en vez de (Int, Int, Tvar) por lo que tendrías que obtener el TVar dentro del IO, algo así como: 
memoria <- IO(Tvar)
El problema que al hacer eso, se crea una nueva memoria compartida, por lo que no funciona bien

**Comment by FedeGB** [comment]
Claro. Me parece que habia probado memoria <- IO(Tvar) pero no se si me devolvia TVar. Tendria que probarlo de vuelta.
Por decis que no funciona bien? Pregunto porque creo que no estoy entendiendo bien el concepto de estas STM.

**Comment by mafvidal** [comment]
Yo lo estuve probando, y lo que creo que pasa, es que cuando haces "**<- IO(Tvar)**" te devuelve un Tvar, pero lo crea ahi, por lo que cada vez que haces un  "**<- IO(Tvar)**" te hace uno nuevo, no podes usarlo como memoria compartida, se entiende?

**Comment by FedeGB** [comment]
Ahh está, ahí entendí. En vez de seguir usando la misma seguis creando nuevas.
Genial, bueno voy a ver como cambiar esa parte entonces.

**Comment by mafvidal** [comment]
Eso mismo, pero todavia no me di cuenta de como hacerlo bien
